## Introduction: Physcian Conversion Model

**An HCP conversion model aims to predict the likelihood of a healthcare provider (HCP) becoming a writer for a particular company or brand for the first time. It helps pharmaceutical or medical device companies identify potential HCPs who have not yet written prescriptions for their products but may be receptive to doing so in the future. The model focuses on converting non-writing HCPs into active writers**

Here's a detailed view of an HCP conversion model:

1. Target Variable: The target variable in an HCP conversion model is binary, indicating whether an HCP becomes a writer (1) or not (0) for a specific company or brand. This variable serves as the outcome to be predicted.

2. Predictive Features: Various data sources and types can be used to develop an HCP conversion model. Some common predictive features include:

	  - Demographic Data: Information about the HCP's age, gender, specialty, location, education level, and other relevant characteristics. Demographic data helps identify patterns and preferences specific to certain groups of HCPs.
	
	  - Claims Data: Historical claims data can provide insights into the HCP's prescribing behavior, utilization patterns, and therapeutic areas of interest. It helps identify HCPs with similar patient profiles or conditions that align with the company's products.
	
	  - Promotional Data: Data on past promotional activities directed at the HCP, such as detailing visits, samples provided, speaker programs attended, and engagement with educational materials. This helps assess the level of previous interaction and the impact of promotional efforts.
	
	  - Network Analysis: Examination of the HCP's professional network, affiliations, collaborations, and referral patterns. Understanding the relationships between HCPs can help identify opinion leaders and assess the impact of peer influence.

**Note: Other types of Features can also be utilized depending on availability and Granularity.**

### Loading Required Libraries and Dependencies

In [2]:
import pandas as pd
import numpy as np
import os

import warnings
warnings.filterwarnings("ignore")

# Visual libraries
import matplotlib.pyplot as plt

# Importing necessary libraries for encoding
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

### Import the dataset and clean column names

In [6]:
import os
import pandas as pd

# Corrected file path
file_path = "/Users/sumanmukherjee_admin/Desktop/Arpa/DS/physician_conversion_mlops-main/data/input/Input_data.csv"

# Check if the file exists
if os.path.exists(file_path):
    # Import the dataset
    df_input = pd.read_csv(file_path)

    # Clean column names
    df_input.columns = df_input.columns.str.strip()
    df_input.columns = df_input.columns.str.replace(' ', '_')

    # Print shape and data format
    print('Shape and data format:')
    print('')
    print(df_input.shape)
else:
    print("File not found at the specified path:", file_path)

Shape and data format:

(5000, 59)

In [7]:
df_input.head()

,NPI_ID,HCP_ID,TARGET,Age,Sex,Specialty,Year_of_Experience,HCO_Affiliation,HCO_Affiliation_Type,Number_of_Rx,...,F2F_visit,F2F_visit_last_1_month,F2F_visit_last_3_month,F2F_visit_last_6_month,F2F_visit_last_12_month,VRC_visit,VRC_visit_last_1_month,VRC_visit_last_3_month,VRC_visit_last_6_month,VRC_visit_last_12_month
0,9846255,HCP_1,0,64,M,Oncology,10,XYZ Medical Center,Referral,290,...,1,2,3,5,9,2,3,5,9,16
1,5217093,HCP_2,1,64,F,Neuro-oncology,47,ABC Medical Center,Collaboration,645,...,2,4,6,8,12,1,2,3,6,11
2,2659257,HCP_3,1,56,M,Hematology,41,STU Medical Center,Employment,879,...,1,2,3,4,6,2,3,6,8,11
3,9851763,HCP_4,1,74,F,Pediatric,35,XYZ Medical Center,Collaboration,392,...,1,2,4,8,15,1,2,4,6,7
4,6650853,HCP_5,0,46,M,Immunology,60,DEF Medical Center,Contract,1043,...,1,2,3,5,8,2,4,6,9,16

### General EDA and Data checks

In [8]:
#General EDA
pd.options.display.max_columns = 50
print()
df_input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 59 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   NPI_ID                              5000 non-null   int64
 1   HCP_ID                              5000 non-null   object
 2   TARGET                              5000 non-null   int64
 3   Age                                 5000 non-null   int64
 4   Sex                                 5000 non-null   object
 5   Specialty                           5000 non-null   object
 6   Year_of_Experience                  5000 non-null   int64
 7   HCO_Affiliation                     5000 non-null   object
 8   HCO_Affiliation_Type                5000 non-null   object
 9   Number_of_Rx                        5000 non-null   int64
 10  Rx_last_1_Month                     5000 non-null   int64
 11  Rx_last_3_Month                     5000 non-null   int64
 12  Rx_last_6_Month                     5000 non-null   int64
 13  Rx_last_12_Month                    5000 non-null   int64
 14  Number_of_Px                        5000 non-null   int64
 15  Px_last_1_Month                     5000 non-null   int64
 16  Px_last_3_Month                     5000 non-null   int64
 17  Px_last_6_Month                     5000 non-null   int64
 18  Px_last_12_Month                    5000 non-null   int64
 19  Claims_last_1_Month                 5000 non-null   int64
 20  Claims_last_3_Month                 5000 non-null   int64
 21  Claims_last_6_Month                 5000 non-null   int64
 22  Claims_last_12_Month                5000 non-null   int64
 23  Procedures_chemo_last_1_month       5000 non-null   int64
 24  Procedures_chemo_last_3_month       5000 non-null   int64
 25  Procedures_chemo_last_6_month       5000 non-null   int64
 26  Procedures_chemo_last_12_month      5000 non-null   int64
 27  Procedures_radio_last_1_month       5000 non-null   int64
 28  Procedures_radio_last_3_month       5000 non-null   int64
 29  Procedures_radio_last_6_month       5000 non-null   int64
 30  Procedures_radio_last_12_month      5000 non-null   int64
 31  Procedures_Immuno_last_1_month      5000 non-null   int64
 32  Procedures_Immuno_last_3_month      5000 non-null   int64
 33  Procedures_Immuno_last_6_month      5000 non-null   int64
 34  Procedures_Immuno_last_12_month     5000 non-null   int64
 35  Procedures_Biopsy_last_1_month      5000 non-null   int64
 36  Procedures_Biopsy_last_3_month      5000 non-null   int64
 37  Procedures_Biopsy_last_6_month      5000 non-null   int64
 38  Procedures_Biopsy_last_12_month     5000 non-null   int64
 39  Promotional_doximity                5000 non-null   int64
 40  Promotional_doximity_last_1_month   5000 non-null   int64
 41  Promotional_doximity_last_3_month   5000 non-null   int64
 42  Promotional_doximity_last_6_month   5000 non-null   int64
 43  Promotional_doximity_last_12_month  5000 non-null   int64
 44  Promotional_medscape                5000 non-null   int64
 45  Promotional_medscape_last_1_month   5000 non-null   int64
 46  Promotional_medscape_last_3_month   5000 non-null   int64
 47  Promotional_medscape_last_6_month   5000 non-null   int64
 48  Promotional_medscape_last_12_month  5000 non-null   int64
 49  F2F_visit                           5000 non-null   int64
 50  F2F_visit_last_1_month              5000 non-null   int64
 51  F2F_visit_last_3_month              5000 non-null   int64
 52  F2F_visit_last_6_month              5000 non-null   int64
 53  F2F_visit_last_12_month             5000 non-null   int64
 54  VRC_visit                           5000 non-null   int64
 55  VRC_visit_last_1_month              5000 non-null   int64
 56  VRC_visit_last_3_month              5000 non-null   int64
 57  VRC_visit_last_6_month              5000 non-null   int64
 58  VRC_visit_last_12_month             5000 non-null   int64
dtypes: int64(54), object(5)
memory usage: 2.3+ MB

In [9]:
df_input.describe()

,NPI_ID,TARGET,Age,Year_of_Experience,Number_of_Rx,Rx_last_1_Month,Rx_last_3_Month,Rx_last_6_Month,Rx_last_12_Month,Number_of_Px,Px_last_1_Month,Px_last_3_Month,Px_last_6_Month,Px_last_12_Month,Claims_last_1_Month,Claims_last_3_Month,Claims_last_6_Month,Claims_last_12_Month,Procedures_chemo_last_1_month,Procedures_chemo_last_3_month,Procedures_chemo_last_6_month,Procedures_chemo_last_12_month,Procedures_radio_last_1_month,Procedures_radio_last_3_month,Procedures_radio_last_6_month,...,Procedures_Immuno_last_12_month,Procedures_Biopsy_last_1_month,Procedures_Biopsy_last_3_month,Procedures_Biopsy_last_6_month,Procedures_Biopsy_last_12_month,Promotional_doximity,Promotional_doximity_last_1_month,Promotional_doximity_last_3_month,Promotional_doximity_last_6_month,Promotional_doximity_last_12_month,Promotional_medscape,Promotional_medscape_last_1_month,Promotional_medscape_last_3_month,Promotional_medscape_last_6_month,Promotional_medscape_last_12_month,F2F_visit,F2F_visit_last_1_month,F2F_visit_last_3_month,F2F_visit_last_6_month,F2F_visit_last_12_month,VRC_visit,VRC_visit_last_1_month,VRC_visit_last_3_month,VRC_visit_last_6_month,VRC_visit_last_12_month
count,5.000000e+03,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.00000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,5.544598e+06,0.250200,60.198200,36.400000,794.586800,1186.889600,1773.687600,2668.695800,4001.142200,183.946000,276.215400,414.737600,620.811400,929.16340,178.329600,268.634400,404.673600,608.417000,49.09620,74.523400,112.546000,168.131200,57.620800,86.995200,130.363800,...,197.662400,57.33700,86.49120,130.503800,196.412800,7.510600,11.781400,18.219800,27.73620,42.021800,7.45780,11.677400,18.056400,27.510000,41.669000,1.502000,2.749000,4.627600,7.436600,11.724200,1.50000,2.748400,4.625800,7.448800,11.645400
std,2.589635e+06,0.433171,18.770258,18.600312,327.511269,546.032458,899.699968,1464.578381,2357.893309,66.730701,114.531764,192.461137,316.462382,517.74319,98.029741,159.358798,256.020525,406.822833,15.36382,27.539425,47.387089,78.760197,13.913408,27.094509,47.897752,...,82.541647,13.84632,26.46427,48.327858,82.397703,1.715948,3.323947,6.164665,10.78209,18.106466,1.71266,3.363211,6.118718,10.584078,18.069044,0.500046,0.825915,1.459638,2.608091,4.587281,0.50005,0.827789,1.463763,2.621899,4.520105
min,1.001849e+06,0.000000,28.000000,10.000000,100.000000,102.000000,106.000000,112.000000,126.000000,70.000000,73.000000,79.000000,91.000000,116.00000,8.000000,9.000000,12.000000,15.000000,23.00000,24.000000,26.000000,32.000000,34.000000,35.000000,38.000000,...,48.000000,34.00000,35.00000,36.000000,46.000000,5.000000,6.000000,7.000000,8.00000,9.000000,5.00000,6.000000,7.000000,8.000000,9.000000,1.000000,2.000000,3.000000,4.000000,5.000000,1.00000,2.000000,3.000000,4.000000,5.000000
25%,3.326632e+06,0.000000,44.000000,17.000000,525.000000,760.000000,1078.000000,1553.000000,2227.750000,126.000000,182.000000,259.000000,384.000000,545.00000,95.000000,136.000000,197.000000,287.750000,35.00000,52.000000,75.000000,109.000000,45.000000,66.000000,95.000000,...,136.000000,45.00000,66.00000,95.000000,135.000000,6.000000,9.000000,14.000000,20.00000,29.000000,6.00000,9.000000,13.000000,20.000000,28.000000,1.000000,2.000000,4.000000,5.000000,8.000000,1.00000,2.000000,4.000000,5.000000,8.000000
50%,5.601028e+06,0.000000,60.000000,40.000000,924.000000,1224.000000,1756.000000,2549.500000,3701.000000,184.000000,266.000000,383.000000,557.000000,808.50000,177.000000,258.000000,371.500000,544.000000,49.00000,72.000000,106.000000,154.000000,58.000000,84.000000,123.000000,...,183.000000,57.00000,83.00000,122.000000,182.000000,8.000000,11.000000,17.000000,26.00000,38.000000,7.00000,11.000000,17.000000,26.000000,38.000000,2.000000,3.000000,4.000000,7.000000,11.000000,1.50000,2.500000,4.000000,7.000000,11.000000
75%,7.752466e+06,1.000000,76.000000,54.000000,1100.000000,1608.000000,2379.000000,3596.250000,5359.250000,241.000000,357.000000,537.000000,804.000000,1208.00000,262.000000,382.000000,573.000000,860.000000,62.00000,94.000000,142.000000,212.000000,70.000000,105.000000,159.000000,...,246.000000,69.00000,104.00000,160.000000,242.250000,9.000000,14.000000,22.000000,34.00000,52.000000,9.00000,14.000000,22.000000,33.000000,52.000000,2.000000,3.000000,6.000000,9.000000,14.000000,2.00000,3.000000,6.000000,9.000000,14.000000
max,9.999327e+06,1.000000,92.000000,60.000000,1100.000000,2198.000000,4281.000000,8083.000000,14285.000000,300.000000,595.000000,1116.000000,2100.000000,3552.00000,350.000000,695.000000,1340.000000,2483.000000,75.00000,150.000000,286.000000,533.000000,81.000000,162.000000,312.000000,...,585.000000,81.00000,162.00000,314.000000,589.000000,10.000000,20.000000,40.000000,74.00000,137.000000,10.00000,20.000000,40.000000,76.000000,130.000000,2.000000,4.000000,8.000000,16.000000,32.000000,2.00000,4.000000,8.000000,16.000000,32.000000

In [10]:
#Check for categorical columns
df_input.select_dtypes('object').nunique()

HCP_ID                  5000
Sex                        2
Specialty                  6
HCO_Affiliation           10
HCO_Affiliation_Type       4
dtype: int64

In [11]:
#Drop unwanted column: "HCO Affiliation" - "Affiliation Type" is more valid column for us
df_input.drop(['HCO_Affiliation'], axis= 1, inplace= True)
print()
print(df_input.select_dtypes('object').nunique())

HCP_ID                  5000
Sex                        2
Specialty                  6
HCO_Affiliation_Type       4
dtype: int64

### Dummy Encode Required Variables

In [13]:
onehot_cols = ['Sex', 'Specialty', 'HCO_Affiliation_Type']

In [14]:
df_input = pd.get_dummies(df_input, columns=onehot_cols, drop_first=True)
print(df_input.shape)
print('')
df_input.head()

(5000, 64)

,NPI_ID,HCP_ID,TARGET,Age,Year_of_Experience,Number_of_Rx,Rx_last_1_Month,Rx_last_3_Month,Rx_last_6_Month,Rx_last_12_Month,Number_of_Px,Px_last_1_Month,Px_last_3_Month,Px_last_6_Month,Px_last_12_Month,Claims_last_1_Month,Claims_last_3_Month,Claims_last_6_Month,Claims_last_12_Month,Procedures_chemo_last_1_month,Procedures_chemo_last_3_month,Procedures_chemo_last_6_month,Procedures_chemo_last_12_month,Procedures_radio_last_1_month,Procedures_radio_last_3_month,...,Promotional_doximity_last_12_month,Promotional_medscape,Promotional_medscape_last_1_month,Promotional_medscape_last_3_month,Promotional_medscape_last_6_month,Promotional_medscape_last_12_month,F2F_visit,F2F_visit_last_1_month,F2F_visit_last_3_month,F2F_visit_last_6_month,F2F_visit_last_12_month,VRC_visit,VRC_visit_last_1_month,VRC_visit_last_3_month,VRC_visit_last_6_month,VRC_visit_last_12_month,Sex_ M,Specialty_Immunology,Specialty_Neuro-oncology,Specialty_Oncology,Specialty_Pediatric,Specialty_Uro-oncology,HCO_Affiliation_Type_Contract,HCO_Affiliation_Type_Employment,HCO_Affiliation_Type_Referral
0,9846255,HCP_1,0,64,10,290,400,492,770,1373,234,464,738,1060,1949,241,395,699,1047,48,82,112,154,43,57,...,47,8,12,18,30,55,1,2,3,5,9,2,3,5,9,16,1,0,0,1,0,0,0,0,1
1,5217093,HCP_2,1,64,47,645,923,1628,2210,2449,80,139,264,318,534,197,266,420,667,66,75,98,124,59,99,...,23,6,11,14,21,40,2,4,6,8,12,1,2,3,6,11,0,0,1,0,0,0,0,0,0
2,2659257,HCP_3,1,56,41,879,1062,1918,3505,6169,197,274,386,642,826,319,532,655,849,37,55,96,129,78,141,...,37,10,17,20,29,48,1,2,3,4,6,2,3,6,8,11,1,0,0,0,0,0,0,1,0
3,9851763,HCP_4,1,74,35,392,704,1036,1078,1184,217,260,319,401,671,232,419,464,849,69,114,139,196,54,69,...,54,6,12,16,21,27,1,2,4,8,15,1,2,4,6,7,0,0,0,0,1,0,0,0,0
4,6650853,HCP_5,0,46,60,1043,1228,1305,1339,2483,209,269,456,591,642,232,261,519,930,75,83,110,163,55,90,...,26,8,12,15,30,52,1,2,3,5,8,2,4,6,9,16,1,1,0,0,0,0,1,0,0

**Note: Save all the Features in Feature Store**

### Feature Selection
- Variance Threshold check
- Select k best for top n features

In [15]:
#it will display all the coulmns for feature selection except the columns mentioned using difference function.
id_target_col_list = ['NPI_ID', 'HCP_ID', 'TARGET']
col_for_feature_selection = df_input.columns.difference(id_target_col_list)

In [16]:
from sklearn.feature_selection import VarianceThreshold

var_thr = VarianceThreshold(threshold = 0.1) #Removing both constant and quasi-constant using theshold, the colums with variance
#<0.1 will not be used for feature selection
var_thr.fit(df_input[col_for_feature_selection])

var_thr.get_support() #to get the output in boolean

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [17]:
df_input_subset = df_input[col_for_feature_selection]
df_input_subset.columns

Index(['Age', 'Claims_last_12_Month', 'Claims_last_1_Month',
       'Claims_last_3_Month', 'Claims_last_6_Month', 'F2F_visit',
       'F2F_visit_last_12_month', 'F2F_visit_last_1_month',
       'F2F_visit_last_3_month', 'F2F_visit_last_6_month',
       'HCO_Affiliation_Type_Contract', 'HCO_Affiliation_Type_Employment',
       'HCO_Affiliation_Type_Referral', 'Number_of_Px', 'Number_of_Rx',
       'Procedures_Biopsy_last_12_month', 'Procedures_Biopsy_last_1_month',
       'Procedures_Biopsy_last_3_month', 'Procedures_Biopsy_last_6_month',
       'Procedures_Immuno_last_12_month', 'Procedures_Immuno_last_1_month',
       'Procedures_Immuno_last_3_month', 'Procedures_Immuno_last_6_month',
       'Procedures_chemo_last_12_month', 'Procedures_chemo_last_1_month',
       'Procedures_chemo_last_3_month', 'Procedures_chemo_last_6_month',
       'Procedures_radio_last_12_month', 'Procedures_radio_last_1_month',
       'Procedures_radio_last_3_month', 'Procedures_radio_last_6_month',
       'Promotional_doximity', 'Promotional_doximity_last_12_month',
       'Promotional_doximity_last_1_month',
       'Promotional_doximity_last_3_month',
       'Promotional_doximity_last_6_month', 'Promotional_medscape',
       'Promotional_medscape_last_12_month',
       'Promotional_medscape_last_1_month',
       'Promotional_medscape_last_3_month',
       'Promotional_medscape_last_6_month', 'Px_last_12_Month',
       'Px_last_1_Month', 'Px_last_3_Month', 'Px_last_6_Month',
       'Rx_last_12_Month', 'Rx_last_1_Month', 'Rx_last_3_Month',
       'Rx_last_6_Month', 'Sex_ M ', 'Specialty_Immunology',
       'Specialty_Neuro-oncology', 'Specialty_Oncology', 'Specialty_Pediatric',
       'Specialty_Uro-oncology', 'VRC_visit', 'VRC_visit_last_12_month',
       'VRC_visit_last_1_month', 'VRC_visit_last_3_month',
       'VRC_visit_last_6_month', 'Year_of_Experience'],
      dtype='object')

In [18]:
remove_col_list = [col for col in df_input_subset.columns 
          if col not in df_input_subset.columns[var_thr.get_support()]]

remove_col_list

[]

**Note: ALL the columns have some variance hence keep all columns**

### Feature Selection Using Select K Best

In [19]:
#Select top n Features
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

def select_kbest_features(df, target_col,n):
  """
  Selects the top n features from the DataFrame using the SelectKBest algorithm.

  Args:
    df: The DataFrame to select features from.
    n: The number of features to select.

  Returns:
    A list of the top n features.
  """


  selector = SelectKBest(k=n)
  selected_features = selector.fit_transform(df, target_col)
  
  mask = selector.get_support()
  top_n_features = df.columns[mask]

  return top_n_features

In [20]:
id_col_list = ['NPI_ID', 'HCP_ID']
target_col = df_input['TARGET']
top_n_col_list = select_kbest_features(df_input.drop(id_col_list,axis=1),target_col, 30)
print(len(top_n_col_list))
top_n_col_list

30

Index(['TARGET', 'Age', 'Year_of_Experience', 'Number_of_Rx',
       'Rx_last_1_Month', 'Rx_last_3_Month', 'Rx_last_6_Month',
       'Rx_last_12_Month', 'Claims_last_1_Month', 'Claims_last_3_Month',
       'Claims_last_6_Month', 'Claims_last_12_Month',
       'Procedures_chemo_last_1_month', 'Procedures_chemo_last_3_month',
       'Procedures_chemo_last_6_month', 'Procedures_chemo_last_12_month',
       'Procedures_radio_last_6_month', 'Procedures_radio_last_12_month',
       'Procedures_Biopsy_last_6_month', 'Promotional_medscape',
       'Promotional_medscape_last_1_month',
       'Promotional_medscape_last_3_month',
       'Promotional_medscape_last_6_month',
       'Promotional_medscape_last_12_month', 'Sex_ M ', 'Specialty_Oncology',
       'Specialty_Pediatric', 'Specialty_Uro-oncology',
       'HCO_Affiliation_Type_Contract', 'HCO_Affiliation_Type_Referral'],
      dtype='object')

In [21]:
#Convert to list
top_n_col_list = top_n_col_list.tolist()


type(top_n_col_list)

list

In [22]:
cols_for_model_df_list = id_col_list + top_n_col_list
print(len(cols_for_model_df_list))
print('')

32

In [23]:
df_feature_eng_output = df_input[cols_for_model_df_list]
df_feature_eng_output.head()

,NPI_ID,HCP_ID,TARGET,Age,Year_of_Experience,Number_of_Rx,Rx_last_1_Month,Rx_last_3_Month,Rx_last_6_Month,Rx_last_12_Month,Claims_last_1_Month,Claims_last_3_Month,Claims_last_6_Month,Claims_last_12_Month,Procedures_chemo_last_1_month,Procedures_chemo_last_3_month,Procedures_chemo_last_6_month,Procedures_chemo_last_12_month,Procedures_radio_last_6_month,Procedures_radio_last_12_month,Procedures_Biopsy_last_6_month,Promotional_medscape,Promotional_medscape_last_1_month,Promotional_medscape_last_3_month,Promotional_medscape_last_6_month,Promotional_medscape_last_12_month,Sex_ M,Specialty_Oncology,Specialty_Pediatric,Specialty_Uro-oncology,HCO_Affiliation_Type_Contract,HCO_Affiliation_Type_Referral
0,9846255,HCP_1,0,64,10,290,400,492,770,1373,241,395,699,1047,48,82,112,154,79,110,182,8,12,18,30,55,1,1,0,0,0,1
1,5217093,HCP_2,1,64,47,645,923,1628,2210,2449,197,266,420,667,66,75,98,124,111,128,73,6,11,14,21,40,0,0,0,0,0,0
2,2659257,HCP_3,1,56,41,879,1062,1918,3505,6169,319,532,655,849,37,55,96,129,238,355,107,10,17,20,29,48,1,0,0,0,0,0
3,9851763,HCP_4,1,74,35,392,704,1036,1078,1184,232,419,464,849,69,114,139,196,91,177,133,6,12,16,21,27,0,0,1,0,0,0
4,6650853,HCP_5,0,46,60,1043,1228,1305,1339,2483,232,261,519,930,75,83,110,163,122,158,234,8,12,15,30,52,1,0,0,0,1,0

In [24]:
df_model_input = df_feature_eng_output.copy()

In [25]:
#Import the dataset
path1 = "/Users/sumanmukherjee_admin/Desktop/Arpa/DS/physician_conversion_mlops-main/data/input/Input_data.csv"
file_path= path1
#file_path = os.path.join(path1,"data","output", "model_input.csv")
df_model_input.to_csv(file_path)